In [2]:
import torch
print(torch.__version__)

2.6.0+cu124


In [4]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available. Using CPU")

GPU is available
Using GPU: Tesla T4


# Creating Tensor

In [6]:
# using empty
# empty function allocates a memory of the shape provided and does not assign any value just shows whichever value was there in that allocated memorya
a = torch.empty(2, 3)
print(a)

tensor([[-4.5790e-38,  4.3321e-41, -4.5790e-38],
        [ 4.3321e-41,  4.4842e-44,  0.0000e+00]])


In [7]:
# check type
type(a)

torch.Tensor

In [8]:
# using zeros
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
# using ones
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
# using rand
torch.rand(2, 3)

tensor([[0.4125, 0.0641, 0.6016],
        [0.0395, 0.6754, 0.2645]])

In [11]:
# using seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
# using tensor
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
# other ways

# arange
print("Using arange: \n", torch.arange(0, 10, 2))
print("\n")

# using linspace
print("Using linspace: \n", torch.linspace(0, 10, 10))
print("\n")

# using eye
print("using eye to get identity matrix: \n", torch.eye(5))
print("\n")

# using full
print("using full to get a tensor of a particular shape having one particular value: \n", torch.full((3, 3), 5))

Using arange: 
 tensor([0, 2, 4, 6, 8])


Using linspace: 
 tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


using eye to get identity matrix: 
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


using full to get a tensor of a particular shape having one particular value: 
 tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [18]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
x.shape

torch.Size([2, 3])

In [20]:
torch.empty_like(x)

tensor([[8027139001404845942, 8101729904709673074, 8318823038135921012],
        [7526676492813825312, 7021786319678370665, 2308668953518369140]])

In [21]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [22]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [23]:
# you need to mention the type here otherwise error
torch.rand_like(x)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [29]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Data Types

In [25]:
# find data type
x.dtype

torch.int64

In [26]:
# typecasting
torch.tensor([1.0, 2.0, 3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [27]:
torch.tensor([1, 2, 3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [28]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# Mathematical operations

## 1. Scalar operations

In [31]:
x = torch.rand(2, 2)
x

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])

In [32]:
# addition

x + 2

tensor([[2.9969, 2.7565],
        [2.2239, 2.3023]])

In [33]:
# substraction
x - 2

tensor([[-1.0031, -1.2435],
        [-1.7761, -1.6977]])

In [34]:
# multiplication
x * 3

tensor([[2.9907, 2.2695],
        [0.6717, 0.9070]])

In [35]:
# division
x / 3

tensor([[0.3323, 0.2522],
        [0.0746, 0.1008]])

In [36]:
# floor division
(x * 100) // 2

tensor([[49., 37.],
        [11., 15.]])

In [37]:
# mod
((x * 100) // 2) % 2

tensor([[1., 1.],
        [1., 1.]])

In [38]:
# power
x ** 2

tensor([[0.9938, 0.5723],
        [0.0501, 0.0914]])

## 2. Element wise operations

In [39]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

print(a)
print(b)

tensor([[0.1784, 0.8238, 0.5557],
        [0.9770, 0.4440, 0.9478]])
tensor([[0.7445, 0.4892, 0.2426],
        [0.7003, 0.5277, 0.2472]])


In [41]:
# add (element wise)
a + b

# sub (element wise)
a - b

# multiply (element wise)
a * b

# division (element wise)
a / b

# power (element wise)
a ** b

# mode (element wise)
a % b

tensor([[0.1784, 0.3346, 0.0706],
        [0.2767, 0.4440, 0.2063]])

In [42]:
c = torch.tensor([1, -2, 3, -4])

In [43]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [44]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [45]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [46]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [47]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [48]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [49]:
# clamp
#  this will make all the numbers less than 2 as 2 and all the numbers greater than 3 as 3
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

# Reduction operation

In [54]:
e = torch.randint(size = (2, 3), low = 0, high = 10, dtype=torch.float32)
e

tensor([[4., 0., 5.],
        [7., 5., 9.]])

In [55]:
# sum
torch.sum(e)

tensor(30.)

In [56]:
# sum along columns
torch.sum(e, dim=0)

tensor([11.,  5., 14.])

In [57]:
# sum along rows
torch.sum(e, dim=1)

tensor([ 9., 21.])

In [58]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([5.5000, 2.5000, 7.0000])

In [59]:
# median
torch.median(e)

tensor(5.)

In [60]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [61]:
# product
torch.prod(e)

tensor(0.)

In [62]:
# standard deviation
torch.std(e)

tensor(3.0332)

In [63]:
# variance
torch.var(e)

tensor(9.2000)

In [69]:
# argmax
print(torch.argmax(e))
print(torch.argmax(e, dim=0))
print(torch.argmax(e, dim=1))

tensor(5)
tensor([1, 1, 1])
tensor([2, 2])


In [65]:
# argmin
torch.argmin(e)

tensor(1)

### 4. Matrix operations

In [70]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[9, 7, 5],
        [9, 8, 9]])
tensor([[7, 9],
        [2, 6],
        [7, 7]])


In [71]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[112, 158],
        [142, 192]])

In [72]:
vec1 = torch.tensor([1, 2])
vec2 = torch.tensor([3, 4])

# dot product
torch.dot(vec1, vec2)

tensor(11)

In [73]:
# transpose
print(f)
print("\n")
torch.transpose(f, 0, 1)

tensor([[9, 7, 5],
        [9, 8, 9]])




tensor([[9, 9],
        [7, 8],
        [5, 9]])

In [75]:
# determinant
h = torch.randint(size=(3, 3), low =0, high = 10, dtype=torch.float32)
print(h)
torch.det(h)

tensor([[8., 3., 6.],
        [1., 5., 5.],
        [0., 4., 3.]])


tensor(-25.0000)

In [76]:
# inverse

torch.inverse(h)

tensor([[ 0.2000, -0.6000,  0.6000],
        [ 0.1200, -0.9600,  1.3600],
        [-0.1600,  1.2800, -1.4800]])

# Comparison operations

In [77]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[8, 8, 3],
        [3, 5, 0]])
tensor([[6, 4, 0],
        [8, 4, 7]])


In [80]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to
i >= j
# less than equal to
i <= j

tensor([[False, False, False],
        [ True, False,  True]])

### 6. Special functions

In [88]:
k = torch.randint(size=(2,3), low=-5, high=10, dtype=torch.float32)
k

tensor([[ 9., -5., -5.],
        [ 4.,  7.,  7.]])

In [89]:
# log
torch.log(k)

tensor([[2.1972,    nan,    nan],
        [1.3863, 1.9459, 1.9459]])

In [90]:
# exp
torch.exp(k)

tensor([[8.1031e+03, 6.7379e-03, 6.7379e-03],
        [5.4598e+01, 1.0966e+03, 1.0966e+03]])

In [91]:
# sqrt
torch.sqrt(k)

tensor([[3.0000,    nan,    nan],
        [2.0000, 2.6458, 2.6458]])

In [92]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9999, 0.0067, 0.0067],
        [0.9820, 0.9991, 0.9991]])

In [93]:
# softmax
torch.softmax(k, dim=0)

tensor([[9.9331e-01, 6.1442e-06, 6.1442e-06],
        [6.6929e-03, 9.9999e-01, 9.9999e-01]])

In [94]:
# relu
torch.relu(k)

tensor([[9., 0., 0.],
        [4., 7., 7.]])

## Inplace Operations

### just add a "_" at the end of the operation and it becomes inplace

In [95]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.1659, 0.4393, 0.2243],
        [0.8935, 0.0497, 0.1780]])
tensor([[0.3011, 0.1893, 0.9186],
        [0.2131, 0.3957, 0.6017]])


In [96]:
# This forms a completely new memory location and stores a tensor. This is problematic
# in many situations, for example if a very large tensor is there and you do this then it occupies a lot of space
m + n

tensor([[0.4670, 0.6286, 1.1429],
        [1.1066, 0.4454, 0.7796]])

In [99]:
# Lets say we want to get an inplace operation where i want to store the result in the memory location of "m" itself

m.add_(n)

tensor([[0.4670, 0.6286, 1.1429],
        [1.1066, 0.4454, 0.7796]])

In [100]:
m

tensor([[0.4670, 0.6286, 1.1429],
        [1.1066, 0.4454, 0.7796]])

In [101]:
n

tensor([[0.3011, 0.1893, 0.9186],
        [0.2131, 0.3957, 0.6017]])

In [102]:
# similarly torch.relu(m) would create a new tensor in a new memory locaton

torch.relu(m)

tensor([[0.4670, 0.6286, 1.1429],
        [1.1066, 0.4454, 0.7796]])

In [103]:
# instead do
m.relu_()

tensor([[0.4670, 0.6286, 1.1429],
        [1.1066, 0.4454, 0.7796]])

## Copying a Tensor

In [104]:
a = torch.rand(2,3)
a

tensor([[0.4234, 0.5224, 0.4175],
        [0.0340, 0.9157, 0.3079]])

In [105]:
b = a

In [106]:
b

tensor([[0.4234, 0.5224, 0.4175],
        [0.0340, 0.9157, 0.3079]])

the above approach has a problem that it's a shallow copy. So on changing "a" then "b" will also change

In [107]:
print(id(a)==id(b))


True


In [111]:
# use clone function

b = a.clone()
print(b)
print(a)

tensor([[0.4234, 0.5224, 0.4175],
        [0.0340, 0.9157, 0.3079]])
tensor([[0.4234, 0.5224, 0.4175],
        [0.0340, 0.9157, 0.3079]])


In [112]:
print(id(a)==id(b))

False


# Tensor operations on GPU

In [113]:
torch.cuda.is_available()

True

In [114]:
device = torch.device("cuda")

In [115]:
# creating a new tensor on GPU

torch.rand((2, 3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [117]:
# move existing tensor to GPU

b = a.to(device)

In [118]:
b+5

tensor([[5.4234, 5.5224, 5.4175],
        [5.0340, 5.9157, 5.3079]], device='cuda:0')

In [119]:
import time

size = 10000

matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# measure cpu time
start = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
end = time.time()

print(f"CPU time: {end - start}")



matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

# measure gpu time
start = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
torch.cuda.synchronize()
end = time.time()

print(f"GPU time: {end - start}")

CPU time: 14.939978122711182
GPU time: 0.7004501819610596


# Reshaping Tensors

In [121]:
a = torch.ones(4, 4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [123]:
# reshape
# original shape dim' product should be the same as reshaped dim's prod
a.reshape(2, 2, 2, 2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [124]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [125]:
b = torch.rand(2, 3, 4)
b

tensor([[[0.2375, 0.5430, 0.1174, 0.6532],
         [0.5115, 0.3094, 0.7907, 0.7351],
         [0.2693, 0.8009, 0.5839, 0.0061]],

        [[0.4671, 0.8243, 0.2861, 0.7459],
         [0.8487, 0.4059, 0.2883, 0.2220],
         [0.6423, 0.7098, 0.5644, 0.4549]]])

In [126]:
# permute
# (2, 3, 4) originally will now become (4, 2, 3)
b.permute(2, 0, 1)

tensor([[[0.2375, 0.5115, 0.2693],
         [0.4671, 0.8487, 0.6423]],

        [[0.5430, 0.3094, 0.8009],
         [0.8243, 0.4059, 0.7098]],

        [[0.1174, 0.7907, 0.5839],
         [0.2861, 0.2883, 0.5644]],

        [[0.6532, 0.7351, 0.0061],
         [0.7459, 0.2220, 0.4549]]])

In [129]:
# unsqueeze - basically at a given position adds a new dim
# for example lets say we have a tensor
c = torch.rand(226, 226, 3) #typical image size
c.unsqueeze(dim = 1).shape

torch.Size([226, 1, 226, 3])

In [133]:
# squeeze
d = torch.rand(1, 20)
d.squeeze(0).shape

torch.Size([20])

# NumPy and PyTorch

In [134]:
import numpy as np

In [135]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [137]:
b = a.numpy()
b

array([1, 2, 3])

In [138]:
c = np.array([1, 2, 3])
c

array([1, 2, 3])

In [139]:
torch.from_numpy(c)

tensor([1, 2, 3])